name: Pull Request

on:
  push:
    branches: [ main ]
  pull_request_target:
    branches: [ main ]

jobs:
  quality-checks:
    name: Pull Request Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out from GitHub"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        
      - name: "Do the thing"
        uses: ./.github/actions/do-the-thing